In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('data.csv')

In [3]:
df.head()

fever  bodyPain  age  runnyNose  diffBreath  visitedAffectedArea  \
0    102         1   44          1          -1                    1   
1    102         1   16          0           0                    0   
2    103         0   25          1          -1                    0   
3     99         0   20          1          -1                    0   
4    103         1   94          1           1                    0   

   infectionProb  
0              1  
1              0  
2              0  
3              0  
4              0

In [4]:
df.tail()

fever  bodyPain  age  runnyNose  diffBreath  visitedAffectedArea  \
10110     99         1   14          0          -1                    0   
10111     98         1    6          0           0                    1   
10112    100         1   91          1           0                    0   
10113    101         1    4          0           1                    1   
10114    100         1   85          0           0                    1   

       infectionProb  
10110              1  
10111              0  
10112              0  
10113              1  
10114              1

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10115 entries, 0 to 10114
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   fever                10115 non-null  int64
 1   bodyPain             10115 non-null  int64
 2   age                  10115 non-null  int64
 3   runnyNose            10115 non-null  int64
 4   diffBreath           10115 non-null  int64
 5   visitedAffectedArea  10115 non-null  int64
 6   infectionProb        10115 non-null  int64
dtypes: int64(7)
memory usage: 553.2 KB


In [6]:
df.describe()

fever      bodyPain           age     runnyNose    diffBreath  \
count  10115.000000  10115.000000  10115.000000  10115.000000  10115.000000   
mean     100.022145      0.493821     50.642313      0.501236      0.012259   
std        1.423726      0.499987     28.913035      0.500023      0.814303   
min       98.000000      0.000000      1.000000      0.000000     -1.000000   
25%       99.000000      0.000000     25.000000      0.000000     -1.000000   
50%      100.000000      0.000000     51.000000      1.000000      0.000000   
75%      101.000000      1.000000     76.000000      1.000000      1.000000   
max      104.000000      1.000000    100.000000      1.000000      1.000000   

       visitedAffectedArea  infectionProb  
count         10115.000000   10115.000000  
mean              0.507860       0.503707  
std               0.499963       0.500011  
min               0.000000       0.000000  
25%               0.000000       0.000000  
50%               1.000000       1.000000  
75%               1.000000       1.000000  
max               1.000000       1.000000

In [7]:
df['diffBreath'].value_counts()

 1    3416
 0    3407
-1    3292
Name: diffBreath, dtype: int64

In [8]:
import numpy as np

In [9]:
def split_data(data,ratio):
    np.random.seed(42) #
    shuffled=np.random.permutation(len(data))
    test_data_size=int(len(data)*ratio)
    test_indices=shuffled[:test_data_size]
    train_indices=shuffled[test_data_size:]
    return data.iloc[train_indices],data.iloc[test_indices]

In [10]:
train,test=split_data(df,0.2)

In [11]:
train

fever  bodyPain  age  runnyNose  diffBreath  visitedAffectedArea  \
7841    101         0   64          1          -1                    0   
8785    101         0   26          1          -1                    1   
2388    100         0   45          1           0                    1   
1817    101         0   56          1           0                    0   
3125    101         1    7          0           0                    1   
...     ...       ...  ...        ...         ...                  ...   
5734    101         1   51          0          -1                    0   
5191     98         1    4          0           1                    0   
5390     98         0    1          0           1                    1   
860      99         1   58          1           1                    0   
7270    100         0   96          0           1                    1   

      infectionProb  
7841              1  
8785              1  
2388              0  
1817              1  
3125              0  
...             ...  
5734              0  
5191              1  
5390              0  
860               1  
7270              0  

[8092 rows x 7 columns]

In [12]:
len(train)

8092

In [13]:
test

fever  bodyPain  age  runnyNose  diffBreath  visitedAffectedArea  \
9419    100         1   59          0           1                    1   
1472    100         0   17          1           1                    0   
8366    100         1   57          0           0                    1   
9465     99         1   69          0           1                    0   
9389    102         1    5          0          -1                    0   
...     ...       ...  ...        ...         ...                  ...   
9056     99         1   77          1           1                    0   
5807    102         0   89          1          -1                    0   
792     100         0   34          1          -1                    1   
1791     99         0   75          1           0                    0   
7405    102         1   29          1           1                    0   

      infectionProb  
9419              0  
1472              0  
8366              1  
9465              0  
9389              1  
...             ...  
9056              1  
5807              0  
792               1  
1791              1  
7405              1  

[2023 rows x 7 columns]

In [14]:
len(test)

2023

In [15]:
x_train=train[['fever','bodyPain','age','runnyNose','diffBreath','visitedAffectedArea']].to_numpy()
x_test=test[['fever','bodyPain','age','runnyNose','diffBreath','visitedAffectedArea']].to_numpy()

In [16]:
x_train

array([[101,   0,  64,   1,  -1,   0],
       [101,   0,  26,   1,  -1,   1],
       [100,   0,  45,   1,   0,   1],
       ...,
       [ 98,   0,   1,   0,   1,   1],
       [ 99,   1,  58,   1,   1,   0],
       [100,   0,  96,   0,   1,   1]], dtype=int64)

In [17]:
x_test

array([[100,   1,  59,   0,   1,   1],
       [100,   0,  17,   1,   1,   0],
       [100,   1,  57,   0,   0,   1],
       ...,
       [100,   0,  34,   1,  -1,   1],
       [ 99,   0,  75,   1,   0,   0],
       [102,   1,  29,   1,   1,   0]], dtype=int64)

In [18]:
y_train=train[['infectionProb']].to_numpy().reshape(len(train),)
y_test=test[['infectionProb']].to_numpy().reshape(len(test),)

In [19]:
y_train

array([1, 1, 0, ..., 0, 1, 0], dtype=int64)

In [20]:
y_test

array([0, 0, 1, ..., 1, 1, 1], dtype=int64)

In [21]:
from sklearn.linear_model import LogisticRegression 

In [22]:
clf=LogisticRegression()
clf.fit(x_train,y_train)

LogisticRegression()

In [23]:
infection=clf.predict_proba([[104,1,67,1,1,1]]) #returns [[probofinfection],[!probabilityofinfection]]

In [24]:
inf=infection[0][1]

In [25]:
inf

0.5014879351095203